version: '3.8'

services:
  app:
    build: .
    container_name: expense-tracker-api
    restart: always
    ports:
      - "8000:8000"
    environment:
      - ENV=PROD

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/alexgruzdev.space/fullchain.pem:/etc/letsencrypt/live/alexgruzdev.space/fullchain.pem
      - /etc/letsencrypt/live/alexgruzdev.space/privkey.pem:/etc/letsencrypt/live/alexgruzdev.space/privkey.pem
